export const MOCK_MARKET_SCHEDULE = {
  SZSE: { openTime: "09:30", closeTime: "15:00" },
  HKSE: { openTime: "09:30", closeTime: "16:00" },
  NASDAQ: { openTime: "09:30", closeTime: "16:00" },
  LSE: { openTime: "08:00", closeTime: "16:30" },
};

export const MOCK_SSE_HOLIDAYS = [
  {
    exchange: "SHH",
    date: "2026-06-19",
    name: "Dragon Boat Festival",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "SHH",
    date: "2026-05-05",
    name: "Labor Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "SHH",
    date: "2026-05-04",
    name: "Labor Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "SHH",
    date: "2026-05-01",
    name: "Labor Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
];

export const MOCK_HKSE_HOLIDAYS = [
  {
    exchange: "HKSE",
    date: "2027-01-01",
    name: "New Year's Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "HKSE",
    date: "2026-12-31",
    name: "New Year's Eve",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "HKSE",
    date: "2026-12-25",
    name: "Christmas",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "HKSE",
    date: "2026-10-19",
    name: "The day following the Chinese Mid-Autumn Festival",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "HKSE",
    date: "2026-10-01",
    name: "National Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "HKSE",
    date: "2026-07-01",
    name: "Hong Kong Special Administrative Region Establishment Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "HKSE",
    date: "2026-06-19",
    name: "Tuen Ng Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "HKSE",
    date: "2026-05-25",
    name: "The Birthday of the Buddha",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "HKSE",
    date: "2026-05-01",
    name: "Labor Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
];

export const MOCK_NASDAQ_HOLIDAYS = [
  {
    exchange: "NASDAQ",
    date: "2027-03-26",
    name: "Good Friday",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "NASDAQ",
    date: "2027-02-15",
    name: "Presidents' Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "NASDAQ",
    date: "2027-01-18",
    name: "Martin Luther King, Jr. Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "NASDAQ",
    date: "2027-01-01",
    name: "New Year's Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "NASDAQ",
    date: "2026-12-25",
    name: "Christmas",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "NASDAQ",
    date: "2026-12-24",
    name: "Christmas",
    isClosed: null,
    adjOpenTime: null,
    adjCloseTime: "13:00",
    isFullyClosed: false,
  },
  {
    exchange: "NASDAQ",
    date: "2026-11-27",
    name: "Thanksgiving Day",
    isClosed: null,
    adjOpenTime: null,
    adjCloseTime: "13:00",
    isFullyClosed: false,
  },
  {
    exchange: "NASDAQ",
    date: "2026-11-26",
    name: "Thanksgiving Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "NASDAQ",
    date: "2026-09-07",
    name: "Labor Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "NASDAQ",
    date: "2026-07-03",
    name: "Independence Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "NASDAQ",
    date: "2026-06-19",
    name: "Juneteenth",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "NASDAQ",
    date: "2026-05-25",
    name: "Memorial Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
];

export const MOCK_LSE_HOLIDAYS = [
  {
    exchange: "LSE",
    date: "2026-12-31",
    name: "Half day",
    isClosed: null,
    adjOpenTime: "08:00",
    adjCloseTime: "12:30",
    isFullyClosed: false,
  },
  {
    exchange: "LSE",
    date: "2026-12-28",
    name: "Boxing Day",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "LSE",
    date: "2026-12-25",
    name: "Christmas",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "LSE",
    date: "2026-12-24",
    name: "Half day",
    isClosed: null,
    adjOpenTime: "08:00",
    adjCloseTime: "12:30",
    isFullyClosed: false,
  },
  {
    exchange: "LSE",
    date: "2026-08-31",
    name: "Summer Bank Holiday",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "LSE",
    date: "2026-05-25",
    name: "Spring Bank Holiday",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
  {
    exchange: "LSE",
    date: "2026-05-04",
    name: "Early May Bank Holiday",
    isClosed: true,
    adjOpenTime: null,
    adjCloseTime: null,
  },
];
